### ISSUE TITLE
viewBox?

### ISSUE THREAD

**Issue by netfeld** [Fuzzyma/svg.select.js#10]
Really great plugin! Thanks! This unfortunately does not work together with viewBoxed svgs. Dragging works fine but resizing fails. Any chance to add this?

**Comment by Fuzzyma** [comment]
Are you speaking about THIS plugin or svg.resize.js?

**Comment by netfeld** [comment]
Yes: i'm using resize - but even when i just use select() - things are getting funny.

**Comment by Fuzzyma** [comment]
please create a fiddle for your case. I actually tested the script with viewbox so I am curious to know

**Comment by netfeld** [comment]
1
Here is the example with aktual versions i use: 
svg.js 2.1.4, svg.select.js 1.0.5 and svg.resize.js v 1.1.0
http://playground.netfeld.de/svg/index.html
Try the drag

2
And here is a fiddle with versions you are using on https://fuzzyma.github.io/svg.resize.js/demo/
https://jsfiddle.net/0ge47zz5/5/
Drag the registration points -  and look at the mouse position

**Comment by Fuzzyma** [comment]
sorry for not getting back on this that long. I was quite busy. I will try to work on it in the next days
