### ISSUE TITLE
Selecting with the mouse

### ISSUE THREAD

**Issue by GildoMat** [Fuzzyma/svg.select.js#16]
Hi! I'm trying to use svg.select.js on a my own draw editor. The problem is that is impossible select the entity with the mouse.  I have a simple SVG created canvas with svg.draw I have created the entities (some rectangles) every time I put, with the mouse one of it, the software unfocus the last one and focuses the new one. At the end I have the last edited rectangle selected. At this point I enable the event 'mouseon' and like your sample (http://fuzzyma.github.io/svg.select.js/demo/index.html), I am trying to use your code :   SVG.select().select({deepSelect:true}); It doesn't works. I have tryed also with SVG.select().selectize({deepSelect:true}); with or without deep select. It seems not working.
what is wrong in my code?

Thanks for your help.
GildoMat

**Comment by Fuzzyma** [comment]
I did not update the demo to mirror the new `selectize()` method.
To make that clear: `select()` is used by svg.js already. `selectize()` is the new method for that plugin.

Your code should look like:
```javascript
var poly = new SVG('polygon_click').size('100%', '100%')
            .polygon('350,50 283,250 450,122 250,122 416,250')
            .attr('pointer-events',"visible");
 
        poly.on('mousedown', function(e){
            poly.selectize().selectize({deepSelect:true});
        }, false);
```

Also: the event is called `mousedown` and not `mouseon`. However I cant see your problem at this point. Please create a [fiddle](https://jsfiddle.net/) to make that clear!
