### ISSUE TITLE
Selecting ForeignObject

### ISSUE THREAD

**Issue by Santhoshsvg** [Fuzzyma/svg.select.js#21]
[ForObjectDemo.zip](https://github.com/Fuzzyma/svg.select.js/files/258452/ForObjectDemo.zip)

Hi i am using the Foreign Object plugin for creating a editable text.
Basically a DIV inside the foreignobject with Contenteditable Attribute set to TRUE for the DIV object. 
After creating i wanted the ForObject element to be draggaed and resized.

But when the object is selected for resizing (Selectize() method), the Viewport[Outer Rectangle box] of the element is displayed based on the X=0,Y=0 position of the container irrespective of the ForObject position on the SVG container.

The draggable, selectize and the Resize functions are called on the ForObject element.

Thanks in Advance for the help.

**Comment by Fuzzyma** [comment]
sorry for the long wait.
I read your code and dont understand why there is written this:
```javascript

				fObj.mouseover(function(event){
					currentX = this.x();
					currentY = this.y();
				});
				fObj.click(function() {
					this.attr("x", currentX);
					this.attr("y", currentY);
					this.resize().draggable();
					this.selectize();
				});	
```

I also dont know why you insert random commands into the source files of svg.resize and svg.select. Doenst make it easier to debug. In fact it works already very well, when you just select the item and deselect it by clicking on the document or so. The call to resize and draggable can be done everywhere in the initialisation. Also there is a reason why there is written: `pointer-events:none`. You usually dont want emit mouseevents to the overlay

**Comment by Santhoshsvg** [comment]
Thanks a lot ulrich master.

Will remove the unneeded code. The above code actually I wanted to put for keeping the x and y position of the forobj element when the content of the text is being edited.

Now I am not using the code anymore since I am using the jquery drag and resize for the text element alone .

For time being I will close this issue and will get back in case of anything new issue arises.
