### ISSUE TITLE
Exception when option points is false.

### ISSUE THREAD

**Issue by githubdorey** [Fuzzyma/svg.select.js#22]
I am using your library and the https://github.com/wout/svg.draggable.js library together to drag an item but did not want to have any points on the selection rectangle.  When I drag, I get the exception commented below on line 135.  I also made a commment on the fix.  I fixed my local file and can confirm it works.

SelectHandler.prototype.updateRectSelection = function () {
...
        if (this.options.rotationPoint) {
            // if this.options.points == false, set.get(9), should be set.get(1)
            this.rectSelection.set.get(9).center(bbox.width / 2, 20);  // here is the exception: Unable to get property 'center' of undefined or null reference
        }
};

**Comment by Fuzzyma** [comment]
was fixed with 2805085e2a941e0d6c53dbd067912673c07f524f
