### ISSUE TITLE
how to check whether current element is selected or not from Code point of view

### ISSUE THREAD

**Issue by Santhoshsvg** [Fuzzyma/svg.select.js#26]
Is there any way to check the status of the Selectize on an object is true or false.
Something similar to hasAttribute of Javascript.

Thanks in advance.

**Comment by Fuzzyma** [comment]
Not in the public api. Loosk like i missed that. However you can access everything through private stuff:

```javascript
var handler = element.remember('_selectHandler')
// here you go
// handler.rectSelection.isSelected
// handler.pointSelection.isSelected
```

**Comment by Santhoshsvg** [comment]
Thanks a lot Mr.Ulrich

Will check the same and in case of any other queries will get back and open this thread again.

**Comment by outOFFspace** [comment]
Add this feature to public API

**Comment by Fuzzyma** [comment]
feel free to create a PR
