### ISSUE TITLE
How to destroy?

### ISSUE THREAD

**Issue by IonicaBizau** [Fuzzyma/svg.select.js#27]
When `remove`ing an element, the circles should disappear. Is it possible to destroy the selectize instance?

**Comment by IonicaBizau** [comment]
I'm just doing for now:

```js
myElm.remove();
myElm.next().remove();
```

But there should be a better solution to that.

**Comment by Fuzzyma** [comment]
There is no event fired when elements are removed. Maybe thats something worth to add in svg.js.
However you can always deselect the shape before removing.
Something like

```js
myElm.selectize(false, {deepSelect: true}).selectize(false).remove()
```

**Comment by IonicaBizau** [comment]
Oh, I probably didn't do `.selectize(false, {deepSelect: true})` but only `.selectize(false)`. 👍  

Thanks!
