### ISSUE TITLE
Uncaught TypeError: Cannot set property 'detail' of undefined

### ISSUE THREAD

**Issue by damiangill** [Fuzzyma/svg.select.js#4]
the first time clicking on a handle produces this console warning

>Uncaught TypeError: Cannot set property 'detail' of undefined

I tested this in the debugger and it happens as follows

**svg.select.getMoseDownFunc** then fires the event with

```javascript
 _this.el.fire(eventName, {x: ev.pageX, y: ev.pageY});
```
the warning occurs **svg.fire**

```javascript
 return e.events[t].detail = n, this.node.dispatchEvent(e.events[t]), delete e.events[t].detail, this
```
my test code is
```javascript
var draw = SVG('drawing').size(500, 500);
var rect = draw.rect(100, 400).attr({fill: '#f06'}).move(100,100);
rect.select();
```

**Comment by Fuzzyma** [comment]
Looks like you realizes yourself that you use an outdated version of svg.js :D. 

Note that this plugin needs to be rewritten for version 2.0 especially because the function 'select()' is used in svg 2.0
