### ISSUE TITLE
SVG.js 2.0?

### ISSUE THREAD

**Issue by dhardtke** [Fuzzyma/svg.select.js#5]
Hi,

does this plugin (and your other ones) support SVG.js 2.0? If yes, could you update the bower.json please?

**Comment by Fuzzyma** [comment]
Try it yourself and you will get an answer ;). No its not working. Please let me some time to follow up.

**Comment by creatyvtype** [comment]
Hey, we're hoping to be able to use this for a project. Feature freeze is Wednesday. Any chance you'll have it up and running for 2.0 by then?

**Comment by praneybehl** [comment]
I get this error when trying to use along with v2.0:
TypeError: el._parent is not a function
    at new SelectHandler (svg.select.js:10)
    at SVG.extend.select (svg.select.js:295)

**Comment by Fuzzyma** [comment]
I released a new version which contains a quick fix for svg.js v2.
Currently this plugin cant do more or less than the version before but to make it work with all transformations I will need some more time

**Comment by praneybehl** [comment]
Thanks for your effort mate, really appreciate it.
Will wait for the further update.

**Comment by Fuzzyma** [comment]
Ready to rumble.
Resizing is now possible with transformed elements, too.
I will close that for now :)

**Comment by creatyvtype** [comment]
Thank you!
