### ISSUE TITLE
Typo in description

### ISSUE THREAD

**Issue by IonicaBizau** [Fuzzyma/svg.select.js#8]
*of svn.js* -- it should be *svg.js* :smile:

**Comment by Fuzzyma** [comment]
thanks^^

**Comment by IonicaBizau** [comment]
@Fuzzyma You're welcome! Btw, does the [demo](http://fuzzyma.github.io/svg.select.js/demo/index.html) work for you?

**Comment by Fuzzyma** [comment]
yes ofc - I wrote it :D

**Comment by IonicaBizau** [comment]
@Fuzzyma But isn't it supposed to be able to resize/rotate the elements?

**Comment by IonicaBizau** [comment]
Ah, got it. I guess it's another project (svg.resize.js). :smile:

**Comment by Fuzzyma** [comment]
jep^^

**Comment by IonicaBizau** [comment]
@Fuzzyma Lol, please fix the typo in [svg.draw.js](https://github.com/Fuzzyma/svg.draw.js) and [svg.resize.js](https://github.com/Fuzzyma/svg.resize.js). :smile:

**Comment by Fuzzyma** [comment]
I was kinda consistent with this typo^^

**Comment by IonicaBizau** [comment]
:fire: :boom: :+1: 

![](http://cdn.smosh.com/sites/default/files/bloguploads/simpsons-fire.gif)
